apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jukebox-frontend.fullname" . }}
  labels:
    {{- include "jukebox-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jukebox-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jukebox-frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: API_UPSTREAM
              value: {{ .Values.env.API_UPSTREAM | quote }}
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5