replicaCount: 1
imagePullSecrets: []

image:
  repository: ghcr.io/jonwong84/jukebox-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30080

env:
  API_UPSTREAM: http://jukebox-data-manager-rest:5035